controllers_security:
    resource: ../../src/Controller/Security
    type: annotation

controllers_front:
    resource: ../../src/Controller/Front
    type: annotation

controllers_back:
    resource: ../../src/Controller/Back
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
